name: todolist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  animate_do: ^3.3.4
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_slidable: ^3.1.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  simple_animations: ^5.0.2
  sqflite: ^2.3.3+1
  supercharged: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/